config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  ActiveAdmin.routes(self)
  resources :resumes, only: [:index, :new, :create, :destroy]
  resources :contents
  resources :users
root "application#index"
  get 'about' => "application#about"
  get 'index' => "application#index"
  get 'late' => "application#late"
  get 'politics' => "application#politics"
  get 'admin' => "application#admin"
  get 'contact' => "application#contact"
  devise_scope :user do
    get 'account' => "devise/registrations#edit"
    get "sign_in" => "devise/sessions#new"
  end
  get 'admin' => "application/admin/contents#"
  get 'manager' => "manager/contents#"

end

app/models/content.rb
class Content < ActiveRecord::Base
  mount_uploader :image, ContentImageUploader
  belongs_to :user
  has_many :links

  #mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  validates :title, :content, presence: true # Make sure the title is present.

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all
    @users = User.all
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
    @contents = Content.all
    @users = User.all
    @teams = Team.all
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @users = User.all
    @content = Content.new(content_params)
    @content.user_id = current_user.id
    @content.team_id = @users.find(@content.user_id).team_id rescue "Kein T"

    respond_to do |format|
      if @content.save
        UserMailer.new_manager_content(@content.team_id).deliver
        format.html { redirect_to @content, notice: 'Content wurde erfolgreich erstellt.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content wurde aktualisiert.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content wurde gelöscht.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_content
    @content = Content.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def content_params
    params.require(:content).permit(:content, :title, :user_id, :team_id, :image, :image_cache, :link)
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<script>
  $(document).ready(function () {
    var preview = $(".upload-preview img");
    $(".file").change(function (event) {
      var input = $(event.currentTarget);
      var file = input[0].files[0];
      var reader = new FileReader();
      reader.onload = function (e) {
        image_base64 = e.target.result;
        preview.attr("src", image_base64);
      };
      reader.readAsDataURL(file);
    });
  });
</script>

<%= form_for(@content) do |f| %>
    <% if @content.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@content.errors.count, "error") %>Dieser Content kann nicht hochgeladen werden</h2>

          <ul>
            <% @content.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group" style="margin-left:2%;max-width:90%">
      <div class="field">
        <%= f.label "Titel" %><br>
        <%= f.text_field :title, type: "text", align: "center" %>
        <br/>
      </div>
      <div class="field">
        <%= f.label "Linkadresse" %><br>
        <%= f.text_field :link, type: "text", align: "center" %>
        <br/>
      </div>
      <div class="field">
        <%- if @content.image_url.present? %>
            <%= image_tag(@content.image.url) %>
        <% end %><br>
      </div>
      <p>

      <div class="upload-preview">
        <img style="max-width:300px"/>
      </div>
      </p>
      <div class="field">
        <%= f.file_field(:image, class: "file") %>
        <%= f.hidden_field :image_cache %>
      </div>
      <br/>

      <div class="field">

        <%= f.label :content %><br>
        <%= f.text_area :content, class: "form-control", rows: "10" %>
        <br/>

        <div class="actions">
          <%= f.submit %>
        </div>
      </div>
      <div>
        <p>
          <br>
          <%= link_to 'Übersicht', contents_path %>
        </p>
      </div>
<% end %>

</div>

app/views/contents/edit.html.erb
<% if current_user.present? && (current_user.is_admin || current_user.is_manager || current_user.is_fs) %>
    <h1>Content Bearbeiten</h1>

    <%= render 'form' %>

<% end %>

app/views/contents/index.html.erb
<% if current_user.present? && (current_user.is_admin || current_user.is_manager || current_user.is_fs) then %>

    <br/>
    <%= link_to " Neuen Content erstellen ", new_content_path, class: "fa fa-plus fa-2x", style: "color:#20549f" %>
    <br/>
    <br/>

    <table class="table table-bordered table-striped">
      <thead>
      <h3>Übersicht</h3>
      <tr>
        <th style="text-align: center">Titel</th>
        <th><!-- Anzeigen --></th>
        <th style="text-align: center"><!-- Bearbeiten --></th>
        <th><!-- Löschen --></th>
        <th style="text-align: center">Freigegeben</th>
      </tr>
      </thead>
      <tbody>
      <% @contents.each do |content| %>
          <% if current_user.is_admin %>
              <tr>
                <td><%= content.title %></td>
                <td><%= link_to 'Anzeigen', content %></td>
                <td><%= link_to 'Bearbeiten', edit_content_path(content) %></td>
                <td><%= link_to 'Löschen', content, method: :delete, data: {confirm: 'Möchtest du diesen Inhalt wirklich löschen?'} %></td>
                <td>
                  <% if content.ok_admin %>
                      <i class="fa fa-check fa-1" , style="color:green"></i>
                  <% else %>
                      <i class="fa fa-times fa-1" , style="color:red"></i>
                  <% end %>
                </td>
          <% else %>
              <% if (current_user.id == content.user_id) %>
                  <td><%= content.title %></td>
                  <td><%= link_to 'Anzeigen', content %></td>
                  <td><%= link_to 'Bearbeiten', edit_content_path(content) %></td>
                  <td><%= link_to 'Löschen', content, method: :delete, data: {confirm: 'Möchtest du diesen Inhalt wirklich löschen?'} %></td>
                  <td>
                    <% if content.ok_admin %>
                        <i class="fa fa-check fa-1" , style="color:green"></i>
                    <% else %>
                        <i class="fa fa-times fa-1" , style="color:red"></i>
                    <% end %>
                  </td>
              <% end %>
          <% end %>
          </tr>
      <% end %>
      </tbody>
    </table>
    <%= link_to 'Zurück zur Startseite', root_path %>
<% end %>

app/views/contents/new.html.erb
<% if current_user.present? && (current_user.is_admin || current_user.is_manager || current_user.is_fs) then %>
    <style type="text/css">
      #link3 {
        color: blue;
      }
    </style>


    <div class="container" style="max-width:100%">
      <h1>Neuer Content</h1>
      <% if !@content.errors.empty? %>
          <div class="alert alert-error">
            <ul>
              <% @content.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div class="container">
        <%= render 'form' %>
      </div>

<% end %>

<%#= render "application/index" %>
</div>

app/views/contents/show.html.erb
<% if current_user.present? && (current_user.is_admin || current_user.is_manager || current_user.is_fs) %>
    <!-- Wenn man nicht admin ist, soll nur der Content angezeigt werden, den man selber erstellt hat -->

    <% user = @content.user_id %>
    <% if (current_user.id == user) || current_user.is_admin %>
        <p>
          <strong>Titel:</strong>
          <br>
          <%= @content.title %>
        </p>
        <p>
          <strong>Content:</strong>
          <br>
          <%= @content.content %>
        </p>
        <p>
          <% if @content.image? %>
              <strong>Bild:</strong>
              <br>
              <%= @content.image rescue "Kein Bild" %>
              </p>
          <% end %>
          <p>
            <strong>User:</strong>
            <br>
            <%= @users.find(user).firstName rescue "User gelöscht" %>
            <%= @users.find(user).lastName rescue "User gelöscht" %>
          </p>

          <p>
            <strong>Team:</strong>
            <br>
            <% team = @content.team_id %>
            <%= @teams.find(team).teamName rescue "kein Team" %>
          </p>

          <p>
            <strong>Erstellt am:</strong>
            <br>
            <%= @content.created_at.strftime('%d.%m.%Y %H:%M') %>
          </p>
          <% if !(@content.created_at == @content.updated_at) %>
              <p>
                <strong>Aktualisiert am:</strong>
                <br>
                <%= @content.updated_at.strftime('%d.%m.%Y %H:%M') %>
              </p>
          <% end %>
          <strong>Freigegeben:</strong>
          <% if @content.ok_admin %>
              <p> Ja

              <p>
          <% else %>
              <p> Nein </p>
          <% end %>
    <% end %>

    <p>
      <br>
      <%= link_to 'Bearbeiten', edit_content_path %>
    </p>
    <br>
    <p>
      <%= link_to 'Übersicht', contents_path %>
    </p>
<% end %>