config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  ActiveAdmin.routes(self)
  resources :resumes, only: [:index, :new, :create, :destroy]
  resources :contents
  resources :users
root "application#index"
  get 'about' => "application#about"
  get 'index' => "application#index"
  get 'late' => "application#late"
  get 'politics' => "application#politics"
  get 'admin' => "application#admin"
  get 'contact' => "application#contact"
  devise_scope :user do
    get 'account' => "devise/registrations#edit"
    get "sign_in" => "devise/sessions#new"
  end
  get 'admin' => "application/admin/contents#"
  get 'manager' => "manager/contents#"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    @users = User.all
    @contents = Content.all
    @teams = Team.all
    @show_contents = Content.where(ok_admin: true).order(created_at: :desc).limit(10)
  end

  def about
    @users = User.all
    @teams = Team.all
    @appointments = Appointment.all
  end

  def late
    if User.find_by(team_id: "7") != nil
      @user = User.find_by(team_id: "7")
    else
      @user = User.first
    end
    @appointments = Appointment.all
  end

  def politics
    @appointments = Appointment.all
  end

  def contact
    @appointments = Appointment.all
  end


  def authenticate_manager!
    if current_user.present? && (current_user.is_admin || current_user.is_manager)
      true
    else
      flash[:alert] = "Du musst Administrator sein, um diese Seite auf zu rufen!"
      redirect_to new_user_session_path
    end
  end

  def authenticate_admin!
    if current_user.present? && current_user.is_admin
      true
    else
      flash[:alert] = "Du musst Administrator sein, um diese Seite auf zu rufen!"
      redirect_to new_user_session_path
    end
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:studiengang, :email, :firstName, :lastName, :facebook, :avatar, :avatar_cache, :confirmed_at]
    devise_parameter_sanitizer.for(:account_update) << [:password, :password_confirmation, :studiengang, :email, :firstName, :lastName, :facebook, :avatar, :avatar_cache, :remove_avatar, :confirmed_at]
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_about.html.erb
<div class="col-md-4">
  <div id="shadow2" class="widget-container" style="margin:5px 0 10px">
    <div class="panel panel-profile">
      <div class="panel-heading bg-danger clearfix">
        <% if about.avatar? %>
            <%= image_tag about.avatar.url(:mid), class: "img-circle", style: "float:left" %>
        <% else %>
            <%= image_tag 'default.jpg', class: "img-circle", style: "float:left" %>
        <% end %>
        <div style="position:relative; left:-25px">
          <h3 class="ng-binding"><%= about.firstName %></h3>

          <p><%= about.lastName %></p>
        </div>
      </div>
      <ul class="list-group">
        <li class="list-group-item">
          <i class="ti-user" data-toggle="tooltip" title="Hauptaufgabe"></i>
          <% if about.team_id != nil %>
              <%= @teams.find_by(id: about.team_id).teamName %>
          <% else %>
              Keine Angaben
          <% end %>
        </li>
        <li class="list-group-item">
          <i class="ti-book" data-toggle="tooltip" title="Studiengang"></i>
          <% if about.studiengang != nil %>
              <%= about.studiengang %>
          <% else %>
              Keine Angaben
          <% end %>
        </li>
        <li class="list-group-item">
          <i class="ti-facebook" data-toggle="tooltip" title="Facebook"></i>
            <% if about.facebook != nil %>
              <a href="<%= about.facebook %>" target="_blank">Link zu Facebook</a>
          <% else %>
          Keine Angaben
          <% end %>
          </li>
        <li class="list-group-item">
          <a id="shadow" href="#" class="btn btn-primary btn-xs" style="float:right">Nach oben</a>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/application/_index.html.erb
<br><br><br>
<div class="panel panel-info" id="shadow2" style="margin:auto;max-width:95%">
  <div class="panel-heading" style="padding-left:20%">
    <%= content.title %>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-2">
        <div class="widget-container">
          <% if content.image? %>
              <%= image_tag content.image_url(:content), class: "img-responsive" %>
          <% else %>
              <%= image_tag 'fachschaft_content.jpg', class: "img-responsive" %>
          <% end %>
        </div>
      </div>
      <div class="col-md-10">
        <div class="widget-container">
          <%= simple_format(content.content) %>
        </div>
      </div>
    </div>
  </div>
  <div class="panel-footer" style="padding-left:20%">
    <p>Erstellt am:
      <%= content.created_at.strftime('%d.%m.%Y') %>
      von
      <% user = content.user_id %>
      <%= link_to (@users.find(user).fullname), user_path(user) rescue "User gelöscht" %>
    </p>
  </div>
</div>
<br>

app/views/application/_index_timeline.html.erb
<div class="tl-body">
  <div class="tl-entry" id="shadow2">
    <div class="tl-time">
      <small class="text-muted">
        <i class="glyphicon glyphicon-time"></i> &#160;Erstellt: <%= content.created_at.strftime("%d.%m.%Y") %> </small>
    </div>
    <div class="tl-icon btn-icon-round btn-icon btn-icon-thin btn-info faa-parent animated-hover">
      <i class="fa fa-calendar faa-pulse"></i></div>
    <div class="tl-content">

      <div class="timeline-panel">
        <div class="timeline-heading">

          <div class="row">
            <div class="col-md-3">
              <div class="widget-container">
                <% if content.image? %>
                    <%= image_tag content.image_url(:content), class: "img-responsive" %>
                <% else %>
                    <%= image_tag 'fachschaft_content.jpg', class: "img-responsive" %>
                <% end %>
                <br>

                <div style="margin:auto;max-width:100%"><strong>
                  <%= @teams.find(content.team_id).teamName rescue "Allgemein" %></strong>
                </div>
              </div>
            </div>
            <div class="col-md-9">
              <div class="widget-container">
                <h4 class="timeline-title"><%= content.title %></h4>
              </div>
              <div class="timeline-body" style="text-align: center">
                <p><%= simple_format content.content %></p>
                <div class="timeline-footer">
                  <hr>
                  <% if content.link? %>
                      <div class="row">
                        <div class="col-md-6">
                          <div class="widget-container">
                            <div style="margin:auto;max-width:100%">
                              <a href="<%= content.link %>" class="btn btn-primary" , target="_blank"><i class="fa fa-external-link"></i>
                                Link</a>
                            </div>
                          </div>
                        </div>
                        <div class="col-md-6">
                          <div class="widget-container">
                            <p>
                              <% user = content.user_id %>
                              <%= link_to (@users.find(user).fullname), user_path(user) rescue "User gelöscht" %>
                            </p>
                          </div>
                        </div>
                      </div>
                  <% else %>
                      <p>
                        <% user = content.user_id %>
                        <%= link_to (@users.find(user).fullname), user_path(user) rescue "User gelöscht" %>
                      </p>
                  <% end %>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application/about.html.erb
<style type="text/css">
  #link2 {
    color: blue;
  }
</style>
<div id="shadow2" class="panel panel-default" style="margin:0 5px 0 5px">
  <div class="panel-heading"><strong><span class="glyphicon glyphicon-heart blue"></span> Fachschaftsmitglieder</strong>
    <button type="button" id="navbutton" data-toggle="collapse" data-target="#navbar-collapse-2" class="navbar-toggle btn btn-default">
      <span class="glyphicon glyphicon-chevron-down blue"></span></button>
  </div>
  <div class="panel-body">

    <ul class="nav nav-pills" id="navbar-collapse-2">
      <li class="active"><a data-toggle="pill" href="#home">Infos</a></li>
      <li><a data-toggle="pill" href="#menu1">Alle</a></li>
      <li><a data-toggle="pill" href="#menu2">Erstsemester</a></li>
      <li><a data-toggle="pill" href="#menu3">Klausuren</a></li>
      <li><a data-toggle="pill" href="#menu4">Sponsoring</a></li>
      <li><a data-toggle="pill" href="#menu5">Gremienarbeit</a></li>
      <li><a data-toggle="pill" href="#menu6">Veranstaltungen</a></li>
      <li><a data-toggle="pill" href="#menu7">Partys</a></li>
    </ul>

    <div class="tab-content">
      <div id="home" class="tab-pane fade in active">
        <div class="grid-structure">
          <div class="row">
            <%= render partial: "about_info" %>
          </div>
        </div>
      </div>
      <div id="menu1" class="tab-pane fade">
        <div class="grid-structure">
          <div class="row">
            <% @users.where(team_id: ["1", "2", "3", "4", "5", "6"]).order(:firstName).each do |about| %>
                <%= render partial: "about", locals: {about: about} %>
            <% end %>
          </div>
        </div>
      </div>
      <div id="menu2" class="tab-pane fade">
        <div class="grid-structure">
          <div class="row">
            <% @users.where(team_id: "1").order(:firstName).each do |about| %>
                <%= render partial: "about", locals: {about: about} %>
            <% end %>
          </div>
        </div>
      </div>
      <div id="menu3" class="tab-pane fade">
        <div class="grid-structure">
          <div class="row">
            <% @users.where(team_id: "5").order(:firstName).each do |about| %>
                <%= render partial: "about", locals: {about: about} %>
            <% end %>
          </div>
        </div>
      </div>
      <div id="menu4" class="tab-pane fade">
        <div class="grid-structure">
          <div class="row">
            <% @users.where(team_id: "3").order(:firstName).each do |about| %>
                <%= render partial: "about", locals: {about: about} %>
            <% end %>
          </div>
        </div>
      </div>
      <div id="menu5" class="tab-pane fade">
        <div class="grid-structure">
          <div class="row">
            <% @users.where(team_id: "6").order(:firstName).each do |about| %>
                <%= render partial: "about", locals: {about: about} %>
            <% end %>
          </div>
        </div>
      </div>
      <div id="menu6" class="tab-pane fade">
        <div class="grid-structure">
          <div class="row">
            <% @users.where(team_id: "4").order(:firstName).each do |about| %>
                <%= render partial: "about", locals: {about: about} %>
            <% end %>
          </div>
        </div>
      </div>
      <div id="menu7" class="tab-pane fade">
        <div class="grid-structure">
          <div class="row">
            <% @users.where(team_id: "2").order(:firstName).each do |about| %>
                <%= render partial: "about", locals: {about: about} %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application/contact.html.erb
<style type="text/css">
  #link9 {
    color: blue;
  }
</style>

<div class="panel-body" id="shadow">
  <div class="grid-structure">
    <div class="row">
      <div class="col-md-12">
        <div class="widget-container">
          <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5846.44823681036!2d7.592373886479074!3d51.96807875932184!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47b9ba9f703635e3%3A0xd6f9f285f5b7f50e!2sFachhochschulzentrum%2C+Corrensstra%C3%9Fe+25%2C+48149+M%C3%BCnster!5e0!3m2!1sde!2sde!4v1456315489418" width="600" height="450" frameborder="0" style="border:0;max-width:100%" allowfullscreen></iframe>
          </div>
        </div>
      </div>
    </div>
    <br>

    <div class="row">
      <div class="col-md-12">
        <div class="widget-container">
          <dl class="dl-horizontal" style="max-width:50%;margin:auto">
            <dt>Impressum</dt>
            <dd><p>
              <strong>Fachhochschule Münster</strong>
              <br>
              Fachschaft Wirtschaft
              <br>
              Corrensstraße 25
              <br>
              48149 Münster
              <br>
              Telefon: 0251 83 64 984
              <br>
              Raum: A 417
            </p>

              <p>
                Du hast fragen? Schreib uns:
                <br>
                info@fh-fachschaft.de
              </p></dd>
            <dt>Vertreten durch<br>den Vorstand:</dt>
            <dd>
              <p><%= @appointments.find_by(title: "1. Vorstand").content %></p>

              <p><%= @appointments.find_by(title: "2. Vorstand").content %></p></dd>
            <dt>Haftungshinweis:</dt>
            <dd>Trotz sorgfältiger inhaltlicher Überprüfung übernehmen wir keine Haftung für die Inhalte externer Links.
              Für den Inhalt der verlinkten Seiten sind ausschließlich deren Betreiber verantwortlich.
              Zum Zeitpunkt der Einstellung waren trotz Prüfung keine Rechtsverstöße zu erkennen.
              Sollten uns Links oder Texte mit rechtswidrigen und/oder sittenwidrigen Inhalten bekannt werden,
              werden wir sie umgehend von unserer Seite entfernen.
            </dd>
          </dl>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/application/index.html.erb
<script>
  $(document).ready(function () {
    $("#show").click(function () {
      $("#toggle").fadeToggle("slow");
    });
  });
  $(document).ready(function () {
    $("#show2").click(function () {
      $("#toggle2").fadeToggle("slow");
    });
  });
</script>
<style type="text/css">
  #link1 {
    color: blue;
  }
</style>
<!-- Tabs for the categories -->
<div id="shadow2" style="max-width:100%"><br>
  <ul class="nav nav-tabs" id="shadow2" style="margin:auto;max-width:95%">
    <li class="active"><a data-toggle="tab" href="#news">News</a></li>
    <li><a data-toggle="tab" href="#erstis">Erstemester</a></li>
    <li><a data-toggle="tab" href="#klausuren">Klasusuren</a></li>
    <li><a data-toggle="tab" href="#sponsoring">Sponsoring</a></li>
    <li><a data-toggle="tab" href="#gremien">Gremienarbeit</a></li>
    <li><a data-toggle="tab" href="#veranstaltungen">Veranstaltungen</a></li>
    <li><a data-toggle="tab" href="#partys">Partys</a></li>
    <% if current_user.present? && (current_user.is_admin || current_user.is_manager || current_user.is_fs) %>
        <li><%= link_to "Content Verwalten", contents_path %></li>
    <% end %>
  </ul>


  <div class="tab-content">
    <div id="news" class="tab-pane fade in active">
      <div class="ui-timline-container" style="max-width:100%">
        <!-- Timeline for the newest content (all categories) -->
        <button class="btn btn-primary" id="show"><span class="glyphicon glyphicon-arrow-down"></span>Neueste</button>
        <br><br>
        <section class="ui-timeline" id="toggle">
          <% @show_contents.limit(5).each do |content| %>

              <article class="<%= cycle('tl-item', 'tl-item alt') -%>">
                <%= render partial: "index_timeline", locals: {content: content} %>
              </article>

          <% end %>

        </section>
      </div>

      <div class="ui-timline-container" style="max-width:100%">
        <!-- Timeline for the newest content (all categories) -->
        <button class="btn btn-primary" id="show2"><span class="glyphicon glyphicon-arrow-down"></span>Fast neu</button>
        <br><br>
        <section class="ui-timeline" id="toggle2">
          <% helper = @show_contents.count %>
          <% if helper >5 %>
              <% @show_contents.last(-5+helper).each do |content| %>
                  <article class="<%= cycle('tl-item', 'tl-item alt') -%>">
                    <%= render partial: "index_timeline", locals: {content: content} %>
                  </article>
              <% end %>
          <% end %>

        </section>
      </div>
    </div>
    <!-- Content for Erstsemester -->
    <div id="erstis" class="tab-pane fade">
      <% @contents.where(ok_admin: true).where(team_id: "1").order(created_at: :desc).limit(5).each do |content| %>
          <%= render partial: "index", locals: {content: content} %>
      <% end %>
    </div>

    <!-- Content for Klausuren -->
    <div id="klausuren" class="tab-pane fade">
      <% @contents.where(ok_admin: true).where(team_id: "5").order(created_at: :desc).limit(5).each do |content| %>
          <%= render partial: "index", locals: {content: content} %>
      <% end %>
    </div>


    <!-- Content for Sponsoring -->
    <div id="sponsoring" class="tab-pane fade">
      <% @contents.where(ok_admin: true).where(team_id: "3").order(created_at: :desc).limit(5).each do |content| %>
          <%= render partial: "index", locals: {content: content} %>
      <% end %>
    </div>

    <!-- Content for Gremienarbeit -->
    <div id="gremien" class="tab-pane fade">
      <% @contents.where(ok_admin: true).where(team_id: "6").order(created_at: :desc).limit(5).each do |content| %>
          <%= render partial: "index", locals: {content: content} %>
      <% end %>
    </div>

    <!-- Content for Veranstalstungen -->
    <div id="veranstaltungen" class="tab-pane fade">
      <% @contents.where(ok_admin: true).where(team_id: "4").order(created_at: :desc).limit(5).each do |content| %>
          <%= render partial: "index", locals: {content: content} %>
      <% end %>
    </div>

    <!-- Content for Partys -->
    <div id="partys" class="tab-pane fade">
      <% @contents.where(ok_admin: true).where(team_id: "2").order(created_at: :desc).limit(5).each do |content| %>
          <%= render partial: "index", locals: {content: content} %>
      <% end %>
    </div>

  </div>
</div>

app/views/application/late.html.erb
<style type="text/css">
  #link8 {
    color: blue;
  }
</style>
<script>
  $(document).ready(function () {
    $("#show").click(function () {
      $("#toggle").fadeToggle("slow");
    });
  });
</script>
<script type="text/javascript">
    function confirm_click()
    {
        return confirm("Account ist derzeit gesperrt, danke AStA :D");
    }
</script>
<div style="text-align:center" id="shadow2"><br>

  <h1>O-Woche verpasst und trotzdem gut ins Studium starten?</h1>

  <h1>Kein Problem: <i id="show" style="color:#20549f" class="fa fa-caret-square-o-down faa-float animated"></i>
  </h1>
  <br>

  <div id="toggle" style="display:none">
    <p>Auch wenn Du die O-Woche für deinen Studiengang verpasst hast, kannst Du mit ein wenig Eigeninitiative trotzdem
      erfolgreich ins Studium starten.
      Im Folgenden findest Du unsere spezielle Checkliste für Nachzügler.
      Bei allgemeinen Fragen kannst Du dich gerne an unsere studentische Beratung für Nachzügler wenden.</p>
    <br>

    <p><strong>Dein Ansprechpartner aus der Fachschaft Wirtschaft:</strong></p>

    <p>
      <div style="max-width:400px; margin:auto">
        <div id="shadow2" class="widget-container">
          <div class="panel panel-profile">
            <div class="panel-heading bg-danger clearfix">
              <% if @user.avatar? %>
                  <%= image_tag @user.avatar.url(:mid), class: "img-circle", style: "float:left" %>
              <% else %>
                  <%= image_tag 'default.jpg', class: "img-circle", style: "float:left" %>
              <% end %>
              <div style="position:relative; left:-25px">
                <h3 class="ng-binding"><%= @user.firstName %></h3>
    <p><%= @user.lastName %></p>
  </div>
</div>
<ul class="list-group">
  <li class="list-group-item">
    <i class="ti-email" data-toggle="tooltip" title="E-Mail Adresse"></i>
    <% if current_user.present? %>
        <a href="mailto:info@fh-fachschaft.de?subject=Nachzüglerbetreuung">E-Mail Nachzüglerbetreuung</a>
        </li>
    <% else %>
        <%= link_to "Einloggen um Adresse zu sehen", sign_in_path, class: "btn btn-info" %>
    <% end %>
    <li class="list-group-item">
      <i class="ti-facebook" data-toggle="tooltip" title="Facebook"></i>
      <% if @user.facebook != nil %>
          <a href="<%= @user.facebook %>" target="_blank">Link zu Facebook</a>
      <% else %>
          Keine Angaben
      <% end %>
    </li>
    </ul>
</div>
</div>
</div>
</p>
<p><strong>Termine</strong>
  <br>
  (Studienverlaufsplan, Stundenplanerstellung, Prüfungsanmeldung, Rundgang FHZ und Co.)
  <br>
  <br>
<h4><strong><%= @appointments.find_by(title: "1. Termin Nachzüglerbetreuung").content.html_safe %> </strong>
  <br>
  <br>
  <strong><%= @appointments.find_by(title: "2. Termin Nachzüglerbetreuung").content.html_safe %> </strong></h4>
Bitte melde Dich für einen Termin per Email an.
<br>
</p>
<br><br>

<blockquote class="blockquote-colored" id="shadow_smaller">
  <medium><strong>Wichtig zum Einstieg</strong></medium>
  <p>Mach Dich mit den grundlegenden Hinweisen für Studienstarter auf dieser Webseite vertraut.
    Zusätzlich ist der Erstiguide der Fachschaft Wirtschaft ein praktischer Begleiter,
    der viele Fragen rund um das Studium beantwortet.</p>
</blockquote>
<br>
<blockquote class="blockquote-colored" id="shadow_smaller">
  <medium><strong>Vorlesungsplan</strong></medium>
  <p>Erstelle Deinen Vorlesungsplan, damit Du weißt, wann und wo du welche Vorlesungen, Übungen und Tutorien besuchen
    musst.
    Eine Anleitung für die Stundenplanerstellung findest du auf der Seite für Studienstarter des Fachbereichs.</p>
</blockquote>
<br>
<blockquote class="blockquote-colored" id="shadow_smaller">
  <medium><strong>Vorlesungsmaterialien</strong></medium>
  <p>Professoren und Dozenten stellen für Ihre Vorlesungen Skripte, Übungsaufgaben und andere Dokumente zur Verfügung.
    Diese solltest Du mit in die Vorlesung bringen, um besser folgen zu können (ausgedruckt oder über Laptop/Tablet).
    Die Materialien findest Du entweder im LSF oder im ILIAS unter der entsprechenden Veranstaltung.</p>
</blockquote>
<br>
<blockquote class="blockquote-colored" id="shadow_smaller">
  <medium><strong>Ausweise und Tickets</strong></medium>
  <p>An der Fachhochschule und in Münster benötigst Du einige Ausweise und Tickets, um z.B. Bücher auszuleihen, in
    Mensen zu essen oder
    Dich als Student auszuweisen.
    In der Bibliothek kannst Du einen Ausweis beantragen, um
    Bücher für die Klausurvorbereitung auszuleihen. In der Mensa musst Du mit
    einer Mensakarte bezahlen, um den Studentenpreis zu erhalten. Das
    Semesterticket für den Nahverkehr wird Dir zugeschickt und Deine Studienbescheinigung
    erhälst Du bereits nach Deiner Einschreibung per E-Mail.</p>
</blockquote>
<br>
<blockquote class="blockquote-colored" id="shadow_smaller">
  <medium><strong>Tutorienanmeldung</strong></medium>
  <p>Ab der ersten oder zweiten Vorlesungswoche musst Du Dich im LSF für Tutorien anmelden.</p>
</blockquote>
<br>
<blockquote class="blockquote-colored" id="shadow_smaller">
  <medium><strong>Prüfungsanmeldung</strong></medium>
  <p>Nach Vorlesungsstart hast Du fünf Wochen Zeit Dich im LSF für die Prüfungen am Ende des ersten Semesters
    anzumelden.
    Abmelden kannst Du dich bis eine Woche vor dem Prüfungstermin.</p>
</blockquote>
<br>
<blockquote class="blockquote-colored" id="shadow_smaller">
  <medium><strong>Altklausuren-Verkauf</strong></medium>
  <p>Die Fachschaft Wirtschaft verkauft während der Mittagspause im Fachschaftsbüro A417 Altklausuren, mit denen Du Dich
    auf deine Klausuren vorbereiten kannst.
    Es ist sinnvoll, sich die Klausuren nicht erst am Ende des Semesters zu kaufen, da sie dann teilweise ausverkauft
    sind.</p>
</blockquote>
</div>

<div class="panel-body">
  <div class="divider divider-lg"></div>
  <div>
    <h1>Und diese Infos sind für euch alle Interessant</h1>
    <br>

    <div class="row">
      <div class="col-md-4" id="shadow_ho">
        <div class="ui-bullet">
          <div class="btn-icon btn-icon-round btn-icon-lg bg-danger  faa-parent animated-hover">
            <i class="fa fa-calculator faa-wrench"></i>
          </div>
          <div class="ui-bullet-content">
            <h3><strong>Mathe Brückenkurs</strong></h3>

            <p>Der Mathe Brückenkurs ist freiwillig. Als Vorbereitung auf den Studienstart werden Grundlagen der
              Mathematik wiederholt.<br>
              Wo? Im FHZ, Correnstraße 25.</p>

            <p>
            <h4>Termine werden euch per Mail geschickt.</h4>
            </p>
          </div>
        </div>
      </div>
      <div class="col-md-4" id="shadow_ho">
        <div class="ui-bullet">
          <div class="btn-icon btn-icon-round btn-icon-lg bg-danger">
            <i class="fa fa-beer faa-pulse animated faa-slow"></i>
          </div>
          <div class="ui-bullet-content">
            <h3><strong>O-Woche</strong></h3>

            <p>Deine Chance, die FH Münster, die Stadt und Deine Kommilitonen bereits vor Vorlesungsbeginn kennen
              zulernen. Die Teilnahme ist freiwillig.<br>
              Wo? FHZ, Correnstraße 25.</p>

            <p>
            <h4>Nächster Termin: <br>
              <%= @appointments.find_by(title: "Termin O-Woche").content %></h4>
            </p>
          </div>
        </div>
      </div>
      <div class="col-md-4" id="shadow_ho">
        <div class="ui-bullet">
          <div class="btn-icon btn-icon-round btn-icon-lg bg-danger faa-parent animated-hover">
            <i class="fa fa-bus faa-passing"></i>
          </div>
          <div class="ui-bullet-content">
            <h3><strong>Erstifahrt</strong></h3>

            <p>Traditionell fahren wir mit Euch nach Vorlesungsbeginn ein Wochenende auf Erstifahrt. Die Anmeldung für
              die Erstifahrt findet während der O-Woche statt.</p>

            <p>
            <h4>Nächster Termin: <br>
              <%= @appointments.find_by(title: "Termin Erstifahrt").content %></h4>
            </p>
          </div>

        </div>
      </div>
    </div>

    <div class="divider divider-lg"></div>
    <div class="panel panel-default" style="max-width:450px; margin:auto" id="shadow2">
      <div class="panel-heading">
        <i class="fa fa-facebook-official fa-2x" data-toggle="tooltip" title="Link" style="float:left;color:#20549f"></i>
        Facebook
      </div>
      <div class="panel-body">
        <i class="fa fa-external-link" data-toggle="tooltip" title="Link" style="float:left;color:#20549f"></i>
        <a href="https://www.facebook.com/fhfachschaft/" target="_blank" onclick="return confirm_click();"><strong>Facebook Fachschaft</strong></a>
      </div>
      <div class="panel-body">
        Wir erstellen je Studiengang und Semester immer eine eigene Gruppe. Einfach nach <br>" FH Münster &lt;Studiengang&gt;
        " <br>suchen und beitreten.
      </div>
      <div class="panel-body">
        <i class="fa fa-external-link" data-toggle="tooltip" title="Link" style="float:left;color:#20549f"></i>
        <a href="https://www.facebook.com/fhmuensterwirtschaft/" target="_blank"><strong>Facebook
          Fachbereich</strong></a>
      </div>
      <div class="panel-heading">Die FH bietet zusätzlichen Infos.</div>
      <div class="panel-body">
        <i class="fa fa-external-link" data-toggle="tooltip" title="Link" style="float:left;color:#20549f"></i>
        <a href="https://www.fh-muenster.de/wirtschaft/studienstarter/studienstarter.php" target="_blank"><strong>Studienstarter</strong></a>
      </div>
      <div class="panel-body">
        <i class="fa fa-external-link" data-toggle="tooltip" title="Link" style="float:left;color:#20549f"></i>
        <a href="https://www.fh-muenster.de/wirtschaft/studierende/start/vorlesungszeiten.php" target="_blank"><strong>Vorlesungszeiten</strong></a>
      </div>
    </div>
  </div>
</div>
</div>