config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  ActiveAdmin.routes(self)
  resources :resumes, only: [:index, :new, :create, :destroy]
  resources :contents
  resources :users
root "application#index"
  get 'about' => "application#about"
  get 'index' => "application#index"
  get 'late' => "application#late"
  get 'politics' => "application#politics"
  get 'admin' => "application#admin"
  get 'contact' => "application#contact"
  devise_scope :user do
    get 'account' => "devise/registrations#edit"
    get "sign_in" => "devise/sessions#new"
  end
  get 'admin' => "application/admin/contents#"
  get 'manager' => "manager/contents#"

end

app/models/resume.rb
class Resume < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  validates :name, presence: true # Make sure the owner's name is present.
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  def index
    @resumes = Resume.all
  end

  def new
    @resume = Resume.new
  end

  def create
    @resume = Resume.new(resume_params)

    if @resume.save
      redirect_to resumes_path, notice: "The resume #{@resume.name} has been uploaded."
    else
      render "new"
    end
  end

  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy
    redirect_to resumes_path, notice: "The resume #{@resume.name} has been deleted."
  end

  private
  def resume_params
    params.require(:resume).permit(:name, :attachment)
  end
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/resumes/_form.html.erb
<%= form_for(@resume) do |f| %>
    <% if @resume.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

          <ul>
            <% @resume.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :attachment %><br>
      <%= f.text_field :attachment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/resumes/edit.html.erb
<h1>Datei ändern</h1>

<%= render 'form' %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', resumes_path %>

app/views/resumes/index.html.erb
<style type="text/css">
  #link3 {
    color: blue;
  }
</style>
<div id="shadow2"><br>

  <div class="callout callout-info" id="shadow2" style="margin:auto;max-width:95%">
    <p>
      Erfahrungsberichte über Auslandssemester von Studenten der FH Münster. Wir freuen uns über jeden neuen
      Erfahrungsbericht, den wir hier vorstellen dürfen.
      Schickt ihn einfach im pdf Format an info@fh-fachschaft.de und lasst die Anderen an euren Erfahrungen teilhaben.
    </p>
  </div>
  <br>

  <div class="panel panel-primary" id="shadow2" style="margin:auto;max-width:70%">
    <div class="panel-heading">
      <h3 class="panel-title">Eine Liste der Partnerhochschulen der FH findest du hier :</h3>
    </div>
    <div class="panel-body">
      <a href="https://www.fh-muenster.de/internationaloffice/int_kontakte/index.php" target="_blank">FH Münster</a>
    </div>
  </div>
  <br>
  <% if current_user.present? && current_user.is_admin %>
      <%= link_to " neue Datei hochladen", new_resume_path, class: "fa fa-upload fa-2x", style: "color:#20549f" %>
  <% end %>
  <br/>

  <br/>
  <table class="table table-bordered table-striped" id="shadow2" style="margin:auto;max-width:95%">
    <thead>
    <tr>
      <th></th>
      <th style="text-align: center">Ort</th>
      <th style="text-align: center">Download</th>
      <% if current_user.present? && current_user.is_admin %>
          <th style="text-align: center">Löschen</th>
      <% end %>
    </tr>
    </thead>
    <tbody>
    <% @resumes.each do |resume1| %>
        <tr>
          <td><i class="fa fa-file-pdf-o fa-2x" id="pdf"></i></td>
          <td><strong><%= resume1.name %></strong></td>
          <td><%= link_to "", resume1.attachment_url, class: "fa fa-download fa-2x faa-float animated-hover", style: "color:#20549f", target: "_blank" %></td>
          <% if current_user.present? && current_user.is_admin %>
              <td><%= link_to "", resume1, method: :delete, data: {confirm: "Are you sure that you wish to delete #{resume1.name}?"}, class: "fa fa-times fa-2x", style: "color:red" %>
              </td>
          <% end %>
        </tr>
    <% end %>
    </tbody>
  </table>
  <br>
</div>

app/views/resumes/new.html.erb
<style type="text/css">
  #link3 {
    color: blue;
  }
</style>
<% if current_user.present? && current_user.is_admin %>
    <% if !@resume.errors.empty? %>
        <div class="alert alert-error">
          <ul>
            <% @resume.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="well">
      <%= form_for @resume, html: {multipart: true} do |f| %>
          <%= f.label :name %>
          <%= f.text_field :name %>
          <%= f.file_field :attachment %>
          <%= f.submit "Speichern", class: "btn btn-primary" %>
      <% end %>
      <%= link_to 'Zurück', resumes_path %>
    </div>
<% else %>
    <div class="callout callout-danger">
      <h4>Fehler</h4>

      <p>Böses Ding, hier hast du nichts zu suchen.</p>
    </div>

<% end %>

app/views/resumes/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @resume.name %>
</p>

<p>
  <strong>Attachment:</strong>
  <%= @resume.attachment %>
</p>

<%= link_to 'Edit', edit_resume_path(@resume) %> |
<%= link_to 'Back', resumes_path %>