config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  ActiveAdmin.routes(self)
  resources :resumes, only: [:index, :new, :create, :destroy]
  resources :contents
  resources :users
root "application#index"
  get 'about' => "application#about"
  get 'index' => "application#index"
  get 'late' => "application#late"
  get 'politics' => "application#politics"
  get 'admin' => "application#admin"
  get 'contact' => "application#contact"
  devise_scope :user do
    get 'account' => "devise/registrations#edit"
    get "sign_in" => "devise/sessions#new"
  end
  get 'admin' => "application/admin/contents#"
  get 'manager' => "manager/contents#"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--if lt IE 8html.no-js.lt-ie8
-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->
<head>
  <!-- if IEmeta(http-equiv='X-UA-Compatible', about='IE=edge,chrome=1')
-->
  <title>Fachschaft</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag ('https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,400,600,300,700') %>
  <%= stylesheet_link_tag 'main' %>

  <%= csrf_meta_tags %>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body data-ng-app="app" id="app" class="app" data-custom-page data-off-canvas-nav data-ng-controller="AppCtrl" data-ng-class=" {'layout-boxed': admin.layout === 'boxed'}">
<header class="header navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="row">

      <div class="navbar-header">
        <button type="button" data-toggle="collapse" data-target="#navbar-collapse-1" class="navbar-toggle">
          <span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
        <p class="navbar-brand">Fachschaft Wirtschaft</p>
      </div>

      <div id="navbar-collapse-1" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Startseite", index_path, id: "link1" %></li>
          <li><%= link_to "Über uns", about_path, id: "link2" %></li>
          <li><%= link_to "Erstsemester", late_path, id: "link8" %></li>

          <% if current_user.present? %>
              <li><%= link_to 'Abmelden', destroy_user_session_path, method: :delete %></li>
              <% if current_user.avatar? %>
                  <li>
                    <%= link_to(image_tag(current_user.avatar.url(:thumb), class: "img-circle", style: "margin-top: -15px"), edit_user_registration_path(current_user)) %>
                  </li>
              <% else %>
                  <li>
                    <%= link_to(image_tag('default_header.jpg', class: "img-circle", style: "margin-top: -15px"), edit_user_registration_path(current_user)) %>
                  </li>
              <% end %>
              <% if current_user.present? && current_user.is_admin %>
                  <li>
                    <%= link_to "Administration", admin_users_path, style: "color:red" %>
                  </li>
              <% end %>
              <% if current_user.present? && current_user.is_manager %>
                  <li>
                    <%= link_to "Administration", manager_contents_path, style: "color:red" %>
                  </li>
              <% end %>
          <% else %>
              <li><%= link_to "Einloggen", new_user_session_path, id: "link6" %></li>
              <li><%= link_to "Registrieren", new_user_registration_path, id: "link7" %></li>
          <% end %>
          <li>
            <a href="javascript:;" class="btn btn-default" uib-dropdown-toggle="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="glyphicon glyphicon-chevron-down blue"></span>
            </a>
            <ul class="dropdown-menu with-arrow  pull-right list-langs dropdown-menu-scaleIn" role="menu">
              <li><%= link_to "Auslandsberichte", resumes_path, id: "link3" %></li>

              <!-- Kann erst implementiert werden, sobald der Kalender des anderen Teams vorliegt
              <li><#%= link_to "Events", "#", id: "link4" %></li>-->

              <li><%= link_to "Politik", politics_path, id: "link5" %></li>
              <li><%= link_to "Kontakt/Impressum", contact_path, id: "link9" %></li>
            </ul>
          </li>
        </ul>
      </div>

    </div>
  </div>
</header>

<div class="container">
  <div id="banner" class="banner">
  </div>
  <img id="logo" class="img-responsive" src="<%= asset_path('fachschaftkleiner.png') %>">

  <div class="pages" ng-app="">

    <%= yield %>

  </div>
  <footer id="shadow" class="footer text-center">© Copyright Fachschaft Wirtschaft der FH Münster</footer>
  <!--if lt IE 8
  <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
-->

</div>
</body>
</html>